---
# tasks file for vlipco_nodeapp

- name: Ensure apt-transport-https is installed.
  apt: 
    name: apt-transport-https 
    state: present

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x bionic main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }}.x bionic main"
  register: node_repo

- name: Update apt cache if repo was added.
  apt: 
    update_cache: yes
  when: node_repo.changed

- name: Ensure Node.js and npm are installed.
  apt: 
    name: nodejs={{ nodejs_version }}* 
    state: present

- name: Create directory for app
  file:
      path: "{{ deploy_app_dir }}"
      owner: ubuntu
      group: ubuntu
      mode: 0750
      state: directory

- name: Deploy app from git repo
  git:
      repo: 'https://github.com/oliverjhernandez/http_app.git'
      dest: "{{ deploy_app_dir }}"

- name: Install NPM packages
  npm:
    path: "{{ deploy_app_dir }}"
- name: Copy systemd file
  copy: 
    src: "{{ systemd_file }}"
    dest: "{{ lib_dir }}"
    mode: 0644
  register: systemd_file_status

- name: Link systemd file
  file:
    src: "{{lib_dir}}{{systemd_file}}"
    dest: "{{systemd_dir}}{{systemd_file}}"
    state: link

- name: Reload systemd
  systemd:
      daemon_reload: yes
  when: systemd_file_status.changed

- name: Start http_app service
  systemd:
      name: http_app
      state: started

- name: Start OpenVPN service
  systemd:
      name: openvpn
      state: started
