---
# tasks file for vlipco_monitor

- name: Create directory for script
  file:
    path: "{{ monitor_root }}"
    state: directory

- name: Deploy script
  git:
      repo: 'https://github.com/oliverjhernandez/http_app_monitor.git'
      dest: "{{ monitor_root }}"

- name: Create cron
  cron:
      name: Check HTTP App
      minute: "*/5"
      state: present
      job: "bash {{ monitor_root }}/monitor_http_app.sh -s {{ url }}"
      user: "{{ user }}"
